sudo: required
services:
  - docker

notifications:
  slack:
    #on_success: always
    #on_failure: always
    rooms:
      - secure: kXH5db6WjPbe5pFMlIddrc0MlguZz06KO8sXuYtNMjOedFOPDCUcBOeHaCpVZgVjOP2Xz9Ao+v5Z9R9OyQL7x7YBH+GyOhCdnHJpG6QWP/PzPFzmnVNzvIN29Je/Wctir+HqgqZFTIaBj3XCX8cEBzMjrlgVYozaZBTNStyY9oLIbbGjzpngvl3ibKSw2gL6Myd/L3zdcULi55AsdK9UWwoLzHfSilDQVTGM4xB8C+0ZnVQE4bOgb2VGku/aISWoFFmGAI6/d5CfrqZm7wYcEfI0k6N4ifEGSBOchrygyRsKs2lhspy8/jnqgrD96dJQUq5RMoXMCglJCOsgKy0YqUy8NX9LviWA46lp1cIzn5j5QjAAnZRhvdz9dDRnv2n/EH3RRwDIz//L6CBUw0htdeLFlhzTMT6fHZOFOQaE2k307WrIIsHiBvMePxeYUPjdAyqFraxvJV5UbjNyjpC0GdXQhQUmZERSrQ9HoPRnTLILL7uO/RJWRj89w8nXOH+1h2LxGXI4mmlIGmucDxS3DwOCfarDUpk/i2bCAb0rVfb0LCvfAuyKpFOSbJ6HXElHDsB4cX4pKjk/pXKb8SEIwwakCYMXMvo0sAnyPOxGttVflJa7P7mLnwz7TkX46TZV7ma2ESepyZrAYVnBaNFswbdAtz90yTZLMR4R2jO0jUQ=
